"""empty message

Revision ID: 07dcfb22d61f
Revises: 2637e1956992
Create Date: 2022-09-29 09:38:49.308452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07dcfb22d61f'
down_revision = '2637e1956992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###
