"""empty message

Revision ID: 39720bc05a64
Revises: c28f7d28e88d
Create Date: 2022-10-05 19:32:30.233699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39720bc05a64'
down_revision = 'c28f7d28e88d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('name', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'event', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='unique')
    op.drop_column('event', 'name')
    # ### end Alembic commands ###
