"""empty message

Revision ID: 8d0642914d22
Revises: ae2bab6f5aff
Create Date: 2022-10-23 14:01:37.935518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d0642914d22'
down_revision = 'ae2bab6f5aff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('event_private_key', 'event', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('event_private_key', 'event', ['private'])
    # ### end Alembic commands ###
