"""empty message

Revision ID: d4a91c575911
Revises: 490ab74d1699
Create Date: 2022-10-05 18:38:50.329972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4a91c575911'
down_revision = '490ab74d1699'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('group_private_key', 'group', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('group_private_key', 'group', ['private'])
    # ### end Alembic commands ###
