"""empty message

Revision ID: f809d5a5129e
Revises: 21371ff68c6f
Create Date: 2022-10-12 18:21:17.617264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f809d5a5129e'
down_revision = '21371ff68c6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_participation', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('group_participation_participant_id_fkey', 'group_participation', type_='foreignkey')
    op.create_foreign_key(None, 'group_participation', 'user', ['user_id'], ['id'])
    op.drop_column('group_participation', 'participant_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_participation', sa.Column('participant_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'group_participation', type_='foreignkey')
    op.create_foreign_key('group_participation_participant_id_fkey', 'group_participation', 'user', ['participant_id'], ['id'])
    op.drop_column('group_participation', 'user_id')
    # ### end Alembic commands ###
